### ISSUE TITLE
Missing @param tag

### ISSUE THREAD

**Issue by mniewrzal** [mlocati/php-ide-extensions-helper#1]
Hi,

I had just a moment to take a look but for me it looks very interesting :) I hope I will have time to play with your stubs in near future. Great work! :)

I found small issue :) Params are missing @param tag.

**Comment by mlocati** [comment]
Thanks!  Fixed in https://github.com/mlocati/php-ide-extensions-helper/commit/f7d33dcb8d45d6b50f6ac64ef483950edf693381 (and stubs files updated in https://github.com/mlocati/php-ide-extensions-helper/commit/a6fbe7262134f0195b0058530407f7763a34a41e )
