### ISSUE TITLE
Missing class fields 

### ISSUE THREAD

**Issue by mniewrzal** [mlocati/php-ide-extensions-helper#2]
Hi,

I tried to run PDT code assist tests with your stubs and first thing I noticed is there is no class fields. Compare current Core stub with your version, Exception class:
https://github.com/eclipse/pdt/blob/master/plugins/org.eclipse.php.core/Resources/language/php7.2/Core.php#L152

**Comment by mlocati** [comment]
It's still a work in progress: I still have to add the class parameters (but they are present in the xml files generated from reflection), as well as to complete the extraction of the data from the PHP manual.
But I'm actively working on this project (I just implemented the support for namespaces - see the recent commits).
In any case, thanks for the feedback: it's really appreciated... it's such a big subject that another pairof eyes is really welcome :wink:

**Comment by mniewrzal** [comment]
What I can do right now is to help with testing :) I believe that when PDT tests will not fail with your stubs then its good starting point to think about replacing current solution with yours.

**Comment by mlocati** [comment]
I should have implemented the generation of class fields in the stub files.
